# Generated by Django 4.1.6 on 2023-02-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['created'], 'verbose_name': 'conocimiento', 'verbose_name_plural': 'conocimientos'},
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(blank=True, max_length=180, null=True, verbose_name='Enlace'),
        ),
    ]
